//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module Brownbag.Web.Models {
	export interface BlogPostsViewModel extends Brownbag.Web.Models.PostViewModel
	{
		CreatedByUser: Brownbag.Web.Models.UsersViewModel;
		UpdatedByUser: Brownbag.Web.Models.UsersViewModel;
		CreatedDate: any;
		UpdatedDate: any;
	}
	export interface BlogFKViewModel extends Brownbag.Web.Models.BlogViewModel
	{
		WeatherID: number;
		WeatherCityName: string;
	}
	export interface BlogViewModel
	{
		Id: number;
		Url: string;
		Rating: number;
		Posts: Brownbag.Web.Models.PostViewModel[];
	}
	export interface GuidLookupViewModel
	{
		ID: any;
		Value: string;
	}
	export interface LookupViewModel
	{
		ID: number;
		Value: string;
	}
	export interface PostViewModel
	{
		Id: number;
		Title: string;
		Content: string;
		BlogId: number;
		Blog: any;
	}
	export interface UsersViewModel
	{
		UserFullName: string;
	}
	export interface WeatherForecastViewModel
	{
		DateFormatted: string;
		TemperatureC: number;
		TemperatureF: number;
		Summary: string;
	}
}
module Brownbag.Web.Models.PrimeNG.Grid {
	export interface GridPaginator
	{
		First: number;
		Page: number;
		PageCount: number;
		Rows: number;
	}
	export interface GridViewModel<T> extends Brownbag.Web.Models.PrimeNG.Grid.GridPaginator
	{
		Data: T[];
		Errors: string;
		SearchQuery: string;
	}
}
